# Generated by Django 6.0.2 on 2026-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_alter_repository_connected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestfile',
            name='original_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
