# Generated by Django 6.0.2 on 2026-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_pullrequestfile_original_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnosisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_app_id', models.CharField(blank=True, default='', max_length=50)),
                ('github_installation_id', models.CharField(blank=True, default='', max_length=50)),
                ('github_pem_path', models.CharField(blank=True, default='', max_length=255)),
                ('default_repositories', models.JSONField(default=list)),
                ('enable_llm_analysis', models.BooleanField(default=True)),
                ('enable_tool_backed_analysis', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gnosis Settings',
                'verbose_name_plural': 'Gnosis Settings',
            },
        ),
    ]
