# Generated by Django 6.0.2 on 2026-03-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0005_gnosissettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(blank=True, max_length=100, null=True)),
                ('github_login', models.CharField(blank=True, max_length=255, null=True)),
                ('github_token', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
