# Generated by Django 6.0.2 on 2026-03-07 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner_name', 'repo_name')},
        ),
        # Remove old installation_id first to avoid column name clash with FK
        migrations.RemoveField(
            model_name='repository',
            name='installation_id',
        ),
        migrations.AddField(
            model_name='repository',
            name='github_installation_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='connected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_installation_id', models.CharField(max_length=100, unique=True)),
                ('account_login', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('User', 'User'), ('Organization', 'Organization')], default='User', max_length=20)),
                ('account_id', models.CharField(max_length=100)),
                ('account_avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='platform_app.installation'),
        ),
    ]
