# Generated by Django 6.0.2 on 2026-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_alter_repository_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='repository_selection',
            field=models.CharField(choices=[('all', 'All repositories'), ('selected', 'Selected repositories')], default='all', max_length=20),
        ),
    ]
