def format_pr_summary(pr_result: dict) -> str:
    lines = []

    # Hidden marker (for duplicate detection)
    lines.append("<!-- GNOSIS_PR_REVIEW -->")

    # PR Header
    lines.append("## 🤖 GNOSIS AI PR Review")
    lines.append("")
    lines.append(f"PR #{pr_result['pr_number']}")
    lines.append("")
    lines.append("---")

    # Loop through each file in the PR
    for file in pr_result["files"]:
        lines.append(f"### 📄 {file['filename']}")
        lines.append(f"- **Confidence**: {file['confidence']}")
        lines.append(f"- **Has Fix**: {'Yes' if file['fixed_code'] else 'No'}")

        # Add the review if it exists
        if file.get("review"):
            lines.append(f"### 🔍 Review\n{file['review']}\n")

        # Add the full debug if it exists
        if file.get("full_debug"):
            lines.append(f"<details>\n<summary>Full Debug Details</summary>\n\n{file['full_debug']}\n</details>")

        # Optionally include fixed code if it exists
        if file.get("fixed_code"):
            lines.append(f"### 🛠 Suggested Fix\n```{file['filename'].split('.')[-1]}\n{file['fixed_code']}\n```")
        
        lines.append("")  # Add a space after each file

    lines.append("---")
    lines.append("_Generated by GNOSIS_")

    return "\n".join(lines)