def format_pr_summary(pr_result: dict) -> str:
    lines = []

    # Hidden marker (for duplicate detection)
    lines.append("<!-- GNOSIS_PR_REVIEW -->")

    lines.append("## 🤖 GNOSIS AI PR Review")
    lines.append("")
    lines.append(f"PR #{pr_result['pr_number']}")
    lines.append("")
    lines.append("---")

    for file in pr_result["files"]:
        lines.append(f"### 📄 {file['filename']}")
        lines.append(f"- Confidence: {file['confidence']}")
        lines.append(f"- Has Fix: {'Yes' if file['fixed_code'] else 'No'}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by GNOSIS_")

    return "\n".join(lines)
